const products=[["choc","ช็อกโกแลตเค้ก",89,"🍫🍰"],["straw","สตรอว์เบอร์รีเค้ก",99,"🍓🍰"],["red","เรดเวลเวทเค้ก",89,"🍰"],["blue","บลูเบอร์รีชีสเค้ก",99,"🫐🍰"],["green","มัทฉะเค้ก",89,"🍵🍰"],["carrot","แครอทเค้ก",89,"🥕🍰"]].map(x=>({id:x[0],name:x[1],price:x[2],emoji:x[3]}));
let cart=JSON.parse(localStorage.getItem("baihom-cart")||"[]");
const money=n=>Number(n).toLocaleString("th-TH")+" บาท";
function save(){localStorage.setItem("baihom-cart",JSON.stringify(cart));renderCart()}
function renderProducts(){productGrid.innerHTML=products.map(p=>`<div class="product"><div class="product-img">${p.emoji}</div><h3>${p.name}</h3><p>${money(p.price)}</p><button class="mini-btn" onclick="add('${p.id}')">เพิ่มลงตะกร้า 🛒</button></div>`).join("")}
function add(id){const p=products.find(x=>x.id===id),o=cart.find(x=>x.id===id);o?o.qty++:cart.push({...p,qty:1});save();toast("เพิ่มสินค้าแล้ว")}
function addCustomCake(){let price=+size.value;cart.push({id:"custom-"+Date.now(),name:`เค้กวันเกิด ${price===399?1:price===599?2:3} ปอนด์`,price,qty:1,detail:`${flavor.value}, ${cakeColor.value}, ข้อความ: ${message.value}, รับ: ${pickupDate.value||"ไม่ระบุ"}`});save();toast("เพิ่มเค้กวันเกิดแล้ว")}
function renderCart(){let c=cart.reduce((s,x)=>s+x.qty,0),t=cart.reduce((s,x)=>s+x.price*x.qty,0);cartCount.textContent=c;cartBadge.textContent=c;cartTotal.textContent=money(t);cartItems.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><b>${x.name}</b><br>${money(x.price)} ${x.detail?`<br><small>${x.detail}</small>`:""}<div class="qty"><button onclick="qty(${i},-1)">−</button>${x.qty}<button onclick="qty(${i},1)">+</button><button onclick="del(${i})">ลบ</button></div></div>`).join(""):`<p class="muted">ยังไม่มีสินค้า</p>`}
function qty(i,d){cart[i].qty+=d;if(cart[i].qty<1)cart.splice(i,1);save()} function del(i){cart.splice(i,1);save()}
function openCheckout(){if(!cart.length)return toast("กรุณาเพิ่มสินค้าก่อน");checkoutModal.classList.remove("hidden")}function closeCheckout(){checkoutModal.classList.add("hidden")}
async function placeOrder(){if(!customerName.value.trim()||!phone.value.trim())return toast("กรุณากรอกชื่อและเบอร์โทร");let total=cart.reduce((s,x)=>s+x.price*x.qty,0);let r=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customerName:customerName.value,phone:phone.value,address:address.value,note:checkoutNote.value,items:cart,total})});let d=await r.json();if(!r.ok)return toast(d.error||"เกิดข้อผิดพลาด");cart=[];save();closeCheckout();alert(`สั่งซื้อสำเร็จ 🎉\\nเลขออเดอร์ ${d.id}\\nยอดรวม ${money(d.total)}`)}
function toast(t){toastEl.textContent=t;toastEl.classList.add("show");setTimeout(()=>toastEl.classList.remove("show"),3500)} const toastEl=document.getElementById("toast");
function initAdmin(){customerView.classList.add("hidden");adminView.classList.remove("hidden");if(location.pathname==="/admin")document.title="BaiHom Bakery Admin"}
async function adminLogin(){let r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:adminPassword.value})});if(!r.ok)return toast("รหัสผ่านไม่ถูกต้อง");loginBox.classList.add("hidden");dashboard.classList.remove("hidden");startAdmin()}
async function adminLogout(){await fetch("/api/admin/logout",{method:"POST"});location.reload()}
async function startAdmin(){let r=await fetch("/api/orders");if(r.status===401){loginBox.classList.remove("hidden");dashboard.classList.add("hidden");return}renderAdmin(await r.json());let s=io();s.emit("admin-join");s.on("new-order",o=>{toast(`🔔 ออเดอร์ใหม่ ${o.id}`);if("Notification"in window&&Notification.permission==="granted")new Notification("BaiHom Bakery",{body:`ออเดอร์ ${o.id} ยอด ${money(o.total)}`});renderAdmin([o,...(window.orders||[]).filter(x=>x.id!==o.id)])});s.on("order-updated",loadAdmin);if("Notification"in window&&Notification.permission==="default")Notification.requestPermission()}
async function loadAdmin(){let r=await fetch("/api/orders");if(r.ok)renderAdmin(await r.json())}
function renderAdmin(os){window.orders=os;statAll.textContent=os.length;statPending.textContent=os.filter(x=>x.status==="รอรับออเดอร์").length;statDoing.textContent=os.filter(x=>x.status==="กำลังเตรียม").length;statDone.textContent=os.filter(x=>["พร้อมรับ","จัดส่งแล้ว"].includes(x.status)).length;adminOrders.innerHTML=os.map(o=>`<article class="admin-order"><div class="order-top"><div><h2>🧾 ${o.id}</h2><p><b>${o.customerName}</b> · ${o.phone}</p><small>${new Date(o.createdAt).toLocaleString("th-TH")}</small></div><span class="status">${o.status}</span></div><p>${o.items.map(x=>`${x.name} × ${x.qty} (${money(x.price*x.qty)})${x.detail?`<br><small>↳ ${x.detail}</small>`:""}`).join("<br>")}</p><p>📍 ${o.address||"ไม่ระบุ"}${o.note?`<br>📝 ${o.note}`:""}</p><h3>รวม ${money(o.total)}</h3><div class="order-actions"><button onclick="setStatus('${o.id}','กำลังเตรียม')">รับออเดอร์</button><button onclick="setStatus('${o.id}','พร้อมรับ')">พร้อมรับ</button><button onclick="setStatus('${o.id}','จัดส่งแล้ว')">จัดส่งแล้ว</button><button onclick="setStatus('${o.id}','ยกเลิก')">ยกเลิก</button></div></article>`).join("")||`<div class="admin-order"><p class="muted">ยังไม่มีออเดอร์</p></div>`}
async function setStatus(id,status){await fetch("/api/orders/"+id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});loadAdmin()}
size.addEventListener("change",()=>{sumPrice.textContent=size.value;sumSize.textContent=size.options[size.selectedIndex].text.split(" (")[0]});flavor.addEventListener("change",()=>sumFlavor.textContent=flavor.value);message.addEventListener("input",()=>sumMessage.textContent=message.value);
renderProducts();renderCart();if(location.pathname==="/admin")initAdmin();
if("serviceWorker"in navigator)navigator.serviceWorker.register("/sw.js");